export const STRINGS = {
  app: {
    title: "Whisper Chat",
    metaKeywords: "chat message connect friends",
  },
  nav: {
    profile: "Profile",
    chats: "Chats",
    requests: "Requests",
    home: "Home",
    signUp: "Sign Up",
    signIn: "Sign In",
    ariaLabel: "Main navigation",
  },
  home: {
    heading: "Whisper Chat",
    tagline: "Cozy chats with friends, one message at a time.",
    cta: "Join the Grove",
  },
  auth: {
    username: "Username",
    password: "Password",
    name: "Name",
    mobileNumber: "Mobile Number",
    confirmPassword: "Confirm Password",
    cancel: "Cancel",
    signIn: "Sign In",
    signUp: "Sign up",
    togglePasswordVisibility: "Toggle password visibility",
  },
  validation: {
    nameRequired: "Name is required",
    usernameRequired: "Username is required",
    mobileInvalid: "Please enter valid number.",
    mobileRequired: "Mobile number is required",
    passwordMin: "Enter minimum 8 characters",
    passwordRequired: "Password is required",
    confirmPasswordRequired: "Confirm Password is required",
    passwordsMustMatch: "Passwords must match",
  },
  errors: {
    usernameNotFound: "Username does not exist",
    wrongPassword: "Wrong Password. Try again",
    usernameExists: "Username already exists",
    mobileExists: "Mobile number already exists",
    invalidToken: "Invalid token",
    loadMessages: "Could not load messages. Please try again.",
    loadContacts: "Could not check contact status.",
    loadRequests: "Could not load friend requests.",
  },
  profile: {
    welcome: (name: string) => `Welcome back, ${name}!`,
    signOut: "Sign out",
  },
  chat: {
    contactsTitle: "People",
    contactsEmpty: "No one here yet — invite friends to join!",
    messagePlaceholder: "Type your message...",
    emptyMessages: "No messages yet. Say hello!",
    loadingMessages: "Loading conversation...",
    emptyTitle: "Your grove awaits",
    emptySubtitle: "Pick someone from the left to chat or send a friend request.",
  },
  requests: {
    pageTitle: "Friend Requests",
    emptyTitle: "All quiet on the friend front",
    emptySubtitle: "When someone sends you a request, it will show up here.",
    accept: "Accept",
    reject: "Reject",
    sendRequest: "Send Request",
    requestPending: "Request Pending",
    notFriendTitle: "Not friends yet",
    notFriendSubtitle: "Send a request to start chatting with this person.",
  },
} as const;
